export const CATALOGFETCHPRODUCTS = "CATALOGFETCHPRODUCTS"
export const ADDTOCART = "ADDTOCART"
export const ADDTOWISHLIST = "ADDTOWISHLIST"


export const SHOWSPINNER = "SHOWSPINNER"
export const HIDESPINNER = "HIDESPINNER"
